"""The manifest's hit tables, as the RUNTIME consumes them — a generated Lua module.

`ports/<name>.toml` is what the port WANTS; `mhfu_port.lua` is what runs. Until issue
#17 makes the runtime read the manifest itself, this is the bridge for the two tables
issue #19 is about: every `[[hurtbox]]` and every `[[hitzone]]` state, emitted as one
`P.hit(<port>, {...})` call that `mhfu_port.lua` writes into the running game.

Where they land, and why it is in place (2026-09-11):

* the collision volumes go OVER the host species' own set — the one its
  `game_task.ovl` row points at (`0x09BB8A00 + species*0x1D0`; em75 -> `0x09D58CD0`),
  record by record, then a `bone = 0xFFFF` sentinel. Both engine walkers stop at the
  sentinel, so a shorter list is fine and a longer one is NOT: the records after the
  original sentinel are somebody else's bytes. The runtime truncates at the set's
  original count and says so; `--capacity` lets this tool say so first.
* the damage grid goes over the species' `0x48` state blocks, as many states as the
  manifest authored and the game has (Tigrex: two). This half was already proven live
  on 2026-06-28 (every byte 0xFF -> 411-damage hits); the volumes half is what #19 is
  testing.

The file is REGENERATED, never edited: it carries the manifest path and a content
hash so a stale copy on the memstick is recognisable in `framework.log`.

    python -m mhfu_monster_editor.runtime ports/zinogre.toml            # -> scripts/
    python -m mhfu_monster_editor.runtime ports/zinogre.toml --deploy   # + memstick

Stdlib only, like `manifest.py` — the same layer.
"""
from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional, Sequence

from .manifest import (HITZONE_COLUMNS, HITZONE_ROWS, Hurtbox, HitzoneState,
                       ManifestError, PortManifest, load)

#: where a generated module lives in the repo (beside `mhfu_port.lua`)
SCRIPTS_DIR = Path("framework") / "prx" / "mods" / "lua_host" / "scripts"
#: the local PPSSPP memstick's mods dir — the file the game actually loads
MEMSTICK_MODS = Path.home() / ".config" / "ppsspp" / "PSP" / "PLUGINS" / "mhfu_framework" / "mods"
#: `tools/embed_lua.py` keeps the committed `.lua.h` in step so the Docker build
#: (no python) never has to regenerate it
EMBED_TOOL = Path("tools") / "embed_lua.py"

SHAPE_ID = {"sphere": 0, "capsule": 1}


def _f(v: float) -> str:
    """A Lua float literal that round-trips a float32 and reads like a number."""
    s = repr(float(v))
    return s if "." in s or "e" in s else s + ".0"


def volume_row(h: Hurtbox) -> List[str]:
    """One record as its twelve Lua literals, in RECORD order — bone, shape,
    hitzone_row, part, flags, radius, ax, ay, az, bx, by, bz — so the runtime's
    writer is a straight `for i, v in ipairs(rec)` over the `0x28` layout."""
    a = list(h.offset or (0.0, 0.0, 0.0))
    b = list(h.to or (0.0, 0.0, 0.0)) if h.is_capsule else [0.0, 0.0, 0.0]
    return [str(int(h.bone)), str(SHAPE_ID[h.shape]), str(int(h.hitzone_row or 0)),
            str(int(h.part or 0)), "0x%X" % int(h.flags or 0), _f(h.radius),
            _f(a[0]), _f(a[1]), _f(a[2]), _f(b[0]), _f(b[1]), _f(b[2])]


def content_id(m: PortManifest) -> str:
    """Eight hex digits over the two tables, so the log can name the version."""
    h = hashlib.sha1()
    for v in m.hurtboxes:
        h.update(",".join(volume_row(v)).encode())
        h.update(b";")
    for st in m.hitzones:
        for row in st.rows:
            h.update(bytes(int(x) & 0xFF for x in row))
    return h.hexdigest()[:8]


def lua_hit_module(m: PortManifest, *, capacity: Optional[int] = None,
                   source: str = "") -> str:
    """The Lua text. ``capacity`` is the host set's record count when known —
    the number the runtime cannot exceed in place — and is written into the file
    as a fact for the reader, whatever the count."""
    if not m.hurtboxes and not m.hitzones:
        raise ManifestError("%s authors neither [[hurtbox]] nor [[hitzone]] — "
                            "there is nothing to ship" % (source or m.name))
    for st in m.hitzones:
        if len(st.rows) != HITZONE_ROWS or any(len(r) != len(HITZONE_COLUMNS)
                                                for r in st.rows):
            raise ManifestError("hitzone state %r is not %d rows of %d"
                                % (st.name, HITZONE_ROWS, len(HITZONE_COLUMNS)))
    mod = "%s_hit" % m.name
    cid = content_id(m)
    src = source or ("ports/%s.toml" % m.name)
    over = (len(m.hurtboxes) - capacity) if capacity is not None else 0
    out: List[str] = [
        "-- %s.lua — GENERATED by mhfu_monster_editor.runtime from %s" % (mod, src),
        "-- (%d volume(s), %d grid state(s), id %s). Do not edit: re-export from the"
        % (len(m.hurtboxes), len(m.hitzones), cid),
        "-- editor's Parts panel or `python -m mhfu_monster_editor.runtime %s`." % src,
        "--",
        "-- The port's hit tables as `mhfu_port.lua`'s P.hit() writes them into the",
        "-- running game: the collision volumes IN PLACE over the host species' own set",
        "-- (its game_task.ovl row's +0x240 pointer), sentinel-terminated, and the",
        "-- damage grid over the species' 0x48 state blocks. Both land once the port's",
        "-- entity is live in-area and are re-checked every tick (issue #19).",
    ]
    if capacity is not None:
        out.append("-- Host set capacity: %d record(s)%s." % (
            capacity, " — %d MORE than fit; the runtime truncates and logs" % over
            if over > 0 else ""))
    out += [
        "",
        "mhfu.port = mhfu.port or { _queue = {} }",
        "mhfu.port.mod = mhfu.port.mod or function(n, f) mhfu.port._queue[n] = f end",
        "",
        'mhfu.port.mod("%s", function(P)' % mod,
        '  P.hit("%s", {' % m.name,
        "    species = %d," % m.host_species,
        '    id = "%s",' % cid,
    ]
    if m.hurtboxes:
        out.append("    -- bone, shape(0 sphere/1 capsule), hitzone_row, part, flags, "
                   "radius, ax, ay, az, bx, by, bz")
        out.append("    volumes = {")
        for h in m.hurtboxes:
            note = h.label or ("marker" if h.is_marker else "")
            out.append("      { %s },%s" % (", ".join(volume_row(h)),
                                             ("  -- " + note) if note else ""))
        out.append("    },")
    else:
        out.append("    volumes = nil,   -- the host's own set stays as it is")
    if m.hitzones:
        out.append("    -- per state: %d rows x (%s)" % (HITZONE_ROWS,
                                                        " ".join(HITZONE_COLUMNS)))
        out.append("    grid = {")
        for st in m.hitzones:
            out.append("      {  -- %s" % st.name)
            for row in st.rows:
                out.append("        { %s }," % ", ".join(str(int(x)) for x in row))
            out.append("      },")
        out.append("    },")
    else:
        out.append("    grid = nil,      -- the species grid stays as it is")
    out += ["  })", "end)", ""]
    return "\n".join(out)


def _repo_root(m: PortManifest, root: Optional[Path]) -> Path:
    if root is not None:
        return Path(root)
    if m.path is not None:
        return Path(m.path).resolve().parent.parent      # ports/x.toml -> repo
    return Path.cwd()


def export(m: PortManifest, *, out: Optional[Path] = None, root: Optional[Path] = None,
           capacity: Optional[int] = None, embed: bool = True) -> Path:
    """Write the module into the repo's scripts dir (or ``out``). Returns the path.

    Also refreshes the committed `.lua.h` beside it when `tools/embed_lua.py` is
    there, so `make -C framework/prx` — which has no python — stays buildable.
    """
    repo = _repo_root(m, root).resolve()
    # the manifest is usually loaded by a RELATIVE path (`ports/zinogre.toml`) and
    # the repo root is absolute; `relative_to` refuses that pairing outright, so
    # both sides are resolved first
    src = (str(Path(m.path).resolve().relative_to(repo))
           if m.path and _under(m.path, repo) else "")
    text = lua_hit_module(m, capacity=capacity, source=src)
    path = Path(out) if out is not None else repo / SCRIPTS_DIR / ("%s_hit.lua" % m.name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    tool = repo / EMBED_TOOL
    if embed and tool.exists():
        subprocess.run([sys.executable, str(tool), str(path), str(path) + ".h"],
                       check=True)
    return path


def deploy(path: Path, mods_dir: Path = MEMSTICK_MODS) -> Optional[Path]:
    """Copy a generated module onto the memstick. None if there is no memstick
    here. A running game hot-reloads it; a cold one picks it up at boot."""
    if not mods_dir.is_dir():
        return None
    dst = mods_dir / Path(path).name
    shutil.copyfile(path, dst)
    return dst


def _under(p: Path, root: Path) -> bool:
    try:
        Path(p).resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def host_capacity(m: PortManifest) -> Optional[int]:
    """The host set's record count from `species/emNN.json`, if it is built."""
    try:
        from .intel import find_intel
        si = find_intel(m.host_species)
    except Exception:                                            # noqa: BLE001
        return None
    if si is None or not si.parts.present:
        return None
    return si.parts.capacity


def main(argv: Optional[Sequence[str]] = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("manifest", help="ports/<name>.toml")
    ap.add_argument("-o", "--out", help="write here instead of the repo's scripts dir")
    ap.add_argument("--deploy", action="store_true",
                    help="also copy to %s" % MEMSTICK_MODS)
    ap.add_argument("--capacity", type=int, default=None,
                    help="host set record count (default: from species/emNN.json)")
    ap.add_argument("--no-embed", action="store_true",
                    help="do not refresh the .lua.h beside the module")
    ap.add_argument("--print", action="store_true", help="print the module instead")
    a = ap.parse_args(argv)
    m = load(a.manifest)
    cap = a.capacity if a.capacity is not None else host_capacity(m)
    if a.print:
        sys.stdout.write(lua_hit_module(m, capacity=cap, source=a.manifest))
        return 0
    path = export(m, out=Path(a.out) if a.out else None, capacity=cap,
                  embed=not a.no_embed)
    print("wrote %s (%d volume(s), %d state(s), id %s%s)"
          % (path, len(m.hurtboxes), len(m.hitzones), content_id(m),
             "" if cap is None else ", host capacity %d" % cap))
    if cap is not None and len(m.hurtboxes) > cap:
        print("⚠️ %d volume(s) exceed the host set's %d — the runtime will truncate"
              % (len(m.hurtboxes) - cap, cap))
    if a.deploy:
        dst = deploy(path)
        print("deployed -> %s" % dst if dst else
              "no memstick mods dir at %s — not deployed" % MEMSTICK_MODS)
    return 0


if __name__ == "__main__":                                     # pragma: no cover
    raise SystemExit(main())
